// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-OqCwOQAVXHUYFXitz_fHeozMjkcs9g',
    appId: '1:760177012779:web:4142c7557db36acc31fa6e',
    messagingSenderId: '760177012779',
    projectId: 'animalds-24',
    authDomain: 'animalds-24.firebaseapp.com',
    storageBucket: 'animalds-24.appspot.com',
    measurementId: 'G-YSJGN25Z3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKTf2upqjACgf6fpUSN7vLO41FJdFu2M',
    appId: '1:760177012779:android:1b28371f7b8a6ca131fa6e',
    messagingSenderId: '760177012779',
    projectId: 'animalds-24',
    storageBucket: 'animalds-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyLpoa3h8IKx-wxKXTTJAn7SjTKrORrgs',
    appId: '1:760177012779:ios:7c6f10e70824d2cb31fa6e',
    messagingSenderId: '760177012779',
    projectId: 'animalds-24',
    storageBucket: 'animalds-24.appspot.com',
    iosClientId: '760177012779-opfn0071vkrvoj3stcd8ftklketru8gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyLpoa3h8IKx-wxKXTTJAn7SjTKrORrgs',
    appId: '1:760177012779:ios:7c6f10e70824d2cb31fa6e',
    messagingSenderId: '760177012779',
    projectId: 'animalds-24',
    storageBucket: 'animalds-24.appspot.com',
    iosClientId: '760177012779-opfn0071vkrvoj3stcd8ftklketru8gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3-OqCwOQAVXHUYFXitz_fHeozMjkcs9g',
    appId: '1:760177012779:web:92b99319cd2b7f6431fa6e',
    messagingSenderId: '760177012779',
    projectId: 'animalds-24',
    authDomain: 'animalds-24.firebaseapp.com',
    storageBucket: 'animalds-24.appspot.com',
    measurementId: 'G-M3N0T505GH',
  );

}